FROM php:8.0-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-install pdo pdo_mysql && docker-php-ext-enable pdo && docker-php-ext-enable pdo_mysql
RUN apt-get update && apt-get upgrade -y